name: constructive-ranking
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - nltk
  - praw
  - sentence-transformers
  - pytorch
  - torchvision
  - torchaudio
  - pytest
